/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-08-29 12:07:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.baraza.DB.BDB;
import org.baraza.DB.BQuery;

public final class index_app_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.baraza.DB.BQuery");
    _jspx_imports_classes.add("org.baraza.DB.BDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	session.setAttribute("xmlcnf", "");
	session.invalidate();

	String formSelect = "";
	String resultDiv = request.getParameter("process");
	System.out.println("resultDiv is" +resultDiv);
	String getpassword = request.getParameter("getpassword");
	BDB db = new BDB("java:/comp/env/jdbc/database");
	
	System.out.println("db is " + db);

	boolean canRegister = true;
	String regmsg = "";
	String regsem = db.executeFunction("SELECT max(quarterid) FROM quarters WHERE active = true");
	
	
	if(regsem == null) {
		canRegister = false;
		regsem = db.executeFunction("SELECT max(quarterid) FROM quarters");
		regsem = regsem.substring(0, 9);
		regmsg = "<h3 style='color:red;'>Applications for " + regsem + " Academic year are now closed</h3>";
	} else {
		regsem = regsem.substring(0, 9);
		regmsg = "<h3 style='color:blue;'>Application for " + regsem + " Academic year is now open</h3>";
	}

	if((resultDiv == null) && (getpassword == null)) {
		BQuery rs = new BQuery(db, "SELECT form_id, form_name FROM forms WHERE (use_key = 1) ORDER BY form_id");
		while(rs.moveNext()) formSelect += "\n<option value='" + rs.getString("form_id") + "'>" + rs.getString("form_name") + "</option>";
		rs.close();
	} else if(getpassword != null) {
		String userName = request.getParameter("user_name");
		String userIP = request.getRemoteAddr();
		if(userName == null) userName = "-1";
		userName = userName.toLowerCase();
		String studentExist = db.executeFunction("SELECT entity_id FROM entitys WHERE user_name = '" + userName + "'"); 

		if(userName.indexOf("@")<3) {
			resultDiv = "Ensure the email address entered is proper";
		} else if(studentExist == null) {
			resultDiv = "The email does not exist register as a new applicant";
		} else {
			String inSql = "INSERT INTO sys_reset (entity_id, request_email, login_ip) VALUES (";
			inSql += studentExist + ", '" + userName + "', '" + userIP + "')";
			db.executeQuery(inSql);

			resultDiv = "The password has been sent to your email";
		}
	} else {
		String entityName = request.getParameter("entity_name");
		String userName = request.getParameter("user_name");
		String primaryEmail = request.getParameter("primary_email");
		String primaryTelephone = request.getParameter("primary_telephone");
		String selectionID = request.getParameter("selection_id");
		if(userName == null) userName = "-1";
		if(primaryEmail == null) entityName = "";
		if(primaryTelephone == null) primaryTelephone = "";
		if(selectionID == null) entityName = "1";

		userName = userName.toLowerCase();
		primaryEmail = primaryEmail.toLowerCase();

		if(entityName == null) {
			resultDiv = "The name in manditory";
		} else if(userName.indexOf("@")<3) {
			resultDiv = "Ensure the email address entered is proper";
		} else if(userName.equals(primaryEmail)) {
			String studentExist = db.executeFunction("SELECT user_name FROM entitys WHERE user_name = '" + userName + "'"); 
			if(studentExist == null) {
				String inSql = "INSERT INTO entitys (entity_type_id, org_id, entity_name, user_name, primary_email, primary_telephone, selection_id) VALUES (8, 0, '";
				inSql += entityName + "', '" + userName + "', '" + primaryEmail + "', '" + primaryTelephone + "', '" + selectionID + "')";
				db.executeQuery(inSql);
				
				System.out.println("values entered are" + userName + primaryEmail + primaryTelephone + selectionID);

				resultDiv = db.executeFunction("SELECT first_password FROM entitys WHERE user_name = '" + userName + "'");
				resultDiv = "Application submited; Your user name = " + userName + " and password " + resultDiv;
			} else {
				resultDiv = "The username already exists";
			}
		} else {
			resultDiv = "Ensure the email is the same as the confirmed email.";
		}
	}

	db.close();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- General meta information -->\n");
      out.write("\t<title>UEAB On-line Registration</title>\n");
      out.write("\t<meta name=\"description\" content=\"Baraton University On-line Registration\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("\t<meta name=\"author\" content=\"Dew CIS Solutions LTD\">\n");
      out.write("\t<link href=\"landing/images/favicon.ico\" rel=\"shortcut icon\">\n");
      out.write("\t<!-- // General meta information -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<!-- Load stylesheets -->\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/960.css\" media=\"screen\" /><!-- no need to edit, 960.gs Framework -->\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/screen.css\" media=\"screen\" />\n");
      out.write("\t\t<link id=\"theme-colors\" type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/themes/default.css\" media=\"screen\" /><!-- replace css/themes/xxxxxx.css with the theme you want to use -->\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/print.css\" media=\"print\" />\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/jquery.fancybox-1.3.4.css\" media=\"screen\" /><!-- no need to edit, lightbox css -->\n");
      out.write("\t\t<!--[if lt IE 7]><link type=\"text/css\" rel=\"stylesheet\" href=\"landing/css/ie6.css\" media=\"screen\" /><![endif]-->\n");
      out.write("\t<!-- // Load stylesheets -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<!-- Load Javascript / jQuery -->\n");
      out.write("\t\t<!--[if lt IE 7]><script src=\"http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE7.js\"></script><![endif]-->    \n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"landing/js/superfish-combined.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"landing/js/jquery.cycle.all.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"landing/js/jquery.fancybox-1.3.4.pack.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"landing/js/jquery.tweet.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"landing/js/general.js\"></script>\n");
      out.write("\t<!-- // Load Javascript / jQuery -->\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("    \n");
      out.write("\t<div id=\"outer\" class=\"clearfix\">\n");
      out.write("     \n");
      out.write("\t\t<div id=\"header\" class=\"clearfix\">          \n");
      out.write("        \t\n");
      out.write("        \t<div class=\"container_12\">\n");
      out.write("            \t\n");
      out.write("           \t\t<div class=\"grid_12\" id=\"header-container\">\n");
      out.write("                    \n");
      out.write("                    <div id=\"logo\">\n");
      out.write("                        <h1><a href=\"index.jsp\" title=\"Go to the home page\"><img src=\"landing/images/ueab_logo.png\" alt=\"Logo\" /></a></h1>\n");
      out.write("                    </div><!-- //logo -->\n");
      out.write("                    \n");
      out.write("                    <ul class=\"sf-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("                        <li><a href=\"a_general.jsp?view=1:0\">General Information</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"a_admissions.jsp?view=1:0\">Admission</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("            \t</div><!-- //grid_12 -->\n");
      out.write("            \n");
      out.write("\t\t\t</div><!-- //container_12 -->\n");
      out.write("            \n");
      out.write("        \n");
      out.write("        </div><!-- //header -->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div id=\"main\" class=\"clearfix\">\n");
      out.write("        \t\n");
      out.write("            <div class=\"container_12\">\n");
      out.write("            \t\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- To be safe, specify a width/height when using HTML slides -->\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\" style=\"width:940px; height:186px;\">\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_4 alpha\"><a href=\"landing/images/custom/front-full-1.jpg\"><img src=\"landing/images/custom/front-300by180-1.jpg\" alt=\"Student Studying\" /></a></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_4\"><a href=\"landing/images/custom/front-full-3.jpg\"><img src=\"landing/images/custom/front-300by180-3.jpg\" alt=\"University Library\" /></a></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_4 omega\"><a href=\"landing/images/custom/front-full-2.jpg\"><img src=\"landing/images/custom/front-300by180-2.jpg\" alt=\"Chemistry Lab\" /></a></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div><!--//grid_12-->\n");
      out.write("                \n");
      out.write("                <div class=\"clear\"></div><!--//clear columns-->\n");
      out.write("                \n");
      out.write("                <div id=\"main\" class=\"grid_8\">\n");
      out.write("                    <h2>Online Application</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
      out.print( regmsg );
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"grid_4 iconlist\"><img src=\"landing/images/icons/user32.png\" alt=\"Icon\" class=\"left\"><h5>For Existing Users</h5><a href=\"a_admissions.jsp?view=1:0\"><p>Login Here</p></a></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
			if(resultDiv == null) { 
				if(canRegister) { 
      out.write("\n");
      out.write("                \t<div style=\"display:block;\" id=\"main\" class=\"grid_8\">\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-widget ui-widget-content ui-corner-all form_content\">\n");
      out.write("\t\t\t\t\t\t\t<form class=\"standard\" id=\"baraza\" name=\"baraza\" method=\"post\" action=\"index.app.jsp\">\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"field\" id=\"formtable\">\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 150px; vertical-align: top;\">Full Name * : </td><td><input name=\"entity_name\" class=\"w_50\" size=\"50\" type=\"text\" required=\"true\"></td></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 150px; vertical-align: top;\">Email * : </td><td><input name=\"user_name\" class=\"w_50\" size=\"50\" type=\"email\" id=\"email\" required=\"true\"></td></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 150px; vertical-align: top;\">Confirm Email * : </td><td><input name=\"primary_email\" class=\"w_50\" size=\"50\" type=\"email\" id=\"email_again\" required=\"true\"></td></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 150px; vertical-align: top;\">Phone Number * : </td><td><input name=\"primary_telephone\" class=\"w_50\" size=\"50\" type=\"text\" required=\"true\"></td></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 150px; vertical-align: top;\">Application : </td><td><select class='combobox' name='selection_id'>");
      out.print(formSelect);
      out.write("</select></td></tr>\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"button rounded shadow hovershadow\" name=\"process\" value=\"Create Login\"/>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"button rounded shadow hovershadow\" name=\"getpassword\" value=\"Forgot Password\"/>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div><!--//grid_8-->\n");
				}
			} else { 
      out.write("\n");
      out.write("                \t<div id=\"main\" class=\"grid_8\">\n");
      out.write("\t\t\t\t\t");
      out.print(resultDiv );
      out.write("\n");
      out.write("\t\t\t\t\t</div><!--//grid_8-->\n");
			} 
      out.write("\n");
      out.write("                \n");
      out.write("\t\t\t\t<div>\n");
      out.write("                    \n");
      out.write("\t\t\t\t</div>\n");
      out.write("    \n");
      out.write("              </div><!--//grid_8-->\n");
      out.write("                \n");
      out.write("                 \n");
      out.write("                <div id=\"main\" class=\"grid_4\">\n");
      out.write("                    <div class=\"widget\">\n");
      out.write("                    \t<h3 class=\"widgettitle\">Instructions:</h3>\n");
      out.write("                        <p>Welcome to the ");
      out.print( regsem );
      out.write(" Undergraduate Admissions page. Please follow the instructions carefully. Go to http://registration.ueab.ac.ke/a_admissions.jsp to start the application process.</p>\n");
      out.write("                    \t<h3 class=\"widgettitle\">Step 1 </h3>\n");
      out.write("\t\t\t\t\t\t<p>Create new applicant account.</p>\n");
      out.write("\t\t\t\t\t\t<p>1. Enter your name and email address (a password will be displayed on the page and also sent to your email). This password will be required to access your application if you choose to complete it at another time. Make sure you copy your APPLICATION ID displayed at the top of the Admission Form.</p>\n");
      out.write("\t\t\t\t\t\t<p>2. Complete all information, select exam date and venue, and upload your picture.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<h3 class=\"widgettitle\"></h3>\n");
      out.write("\t\t\t\t\t\t<p>For further assistance you can email : admissions [at] ueab.ac.ke or call +254 721 423592, +254 731 793934</p>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                \t<div class=\"widget\">\n");
      out.write("                    </div>\n");
      out.write("      \n");
      out.write("                    <div class=\"widget\">\n");
      out.write("                    </div>                   \n");
      out.write("                \n");
      out.write("                </div><!--//grid_4-->         \n");
      out.write("        \n");
      out.write("                <div class=\"clear\"></div><!--//clear columns-->\n");
      out.write("                \n");
      out.write("                <div class=\"grid_12\">\n");
      out.write("                     <p class=\"quotebox\">\n");
      out.write("                        <small class=\"right\"> .. as said by <strong>George Bernard Shaw</strong></small>\n");
      out.write("                        We are made wise not by the recollection of our past, but by the responsibility for our future.\n");
      out.write("                    </p>\n");
      out.write("                </div><!--//grid_12-->                \n");
      out.write("                \n");
      out.write("            </div><!-- //container_12 -->\n");
      out.write("        \n");
      out.write("        </div><!-- //main -->\n");
      out.write("  \n");
      out.write("       \t\n");
      out.write("        <div id=\"footer-bottom\" class=\"clearfix\">\n");
      out.write("            <div class=\"container_12\">\n");
      out.write("            \t<div class=\"grid_12\">\n");
      out.write("                    <p class=\"left\">&copy; 2015 - <a href=\"http://www.ueab.ac.ke/\" title=\"UEAB Website\">University of Eastern Africa, Baraton</a> | Powered by \t\t<a href=\"http://www.openbaraza.org\" title=\"Openbaraza\"> Openbaraza</a></p>\n");
      out.write("                    <p class=\"right\"><a href=\"#\" class=\"scroll-top\" title=\"Back to the Top\">TOP</a></p>\n");
      out.write("                </div>\n");
      out.write("            </div><!--//container_12-->\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("\t</div><!-- //outer -->\n");
      out.write("\t\n");
      out.write("\t<!-- insert analytics -->\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
