/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-09-20 09:49:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.baraza.DB.BDB;
import org.baraza.DB.BQuery;

public final class a_005findustry_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.baraza.DB.BQuery");
    _jspx_imports_classes.add("org.baraza.DB.BDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");

    session.setAttribute("xmlcnf", "");
    session.invalidate();

    String formSelect = "";
    String appStatus = "not";
    String resultDiv = request.getParameter("process");
    System.out.println("resultDiv is" +resultDiv);
    String getpassword = request.getParameter("getpassword");
    BDB db = new BDB("java:/comp/env/jdbc/database");

    System.out.println("db is " + db);

    boolean canRegister = true;
    String regmsg = "";

    if(resultDiv == null || resultDiv == "") {
        regmsg = "Register Company";
    } else if(getpassword != null) {
        String user_name = request.getParameter("user_name");
        String email = request.getParameter("email");
        String userIP = request.getRemoteAddr();

        if(user_name == null) user_name = "-1";
        user_name = user_name.toLowerCase();
        String userExists = db.executeFunction("SELECT user_name FROM entitys WHERE user_name = '" + user_name + "'");

        if(email.indexOf("@")<3) {
            appStatus = "ok";
            resultDiv = "<div class='alert alert-danger'>Ensure the email address entered is proper.</div>";
        } else if(userExists == null) {
            resultDiv = "<div class='alert alert-danger'>The User does not exist register as a new applicant.</div>";
        } else {
            String inSql = "INSERT INTO sys_reset (entity_id, request_email, login_ip) VALUES (";
            inSql += userExists + ", '" + email + "', '" + userIP + "')";
            db.executeQuery(inSql);

            resultDiv = "The password has been sent to your email";
        }
    } else {
        String user_name = request.getParameter("user_name");
        String email = request.getParameter("email");
        String password = request.getParameter("password");
        String confirm_password = request.getParameter("confirm_password");
    if(email == null) {
      resultDiv = "<div class='alert alert-danger'>The name in manditory</div>";
    } else if(email.indexOf("@")<3) {
    appStatus = "ok";
    resultDiv = "<div class='alert alert-danger'>Ensure the email address entered is proper</div>";
    } else if(password.equals(confirm_password)) {
      String userExists = db.executeFunction("SELECT user_name FROM entitys WHERE user_name = '" + user_name + "'");
      if(userExists == null) {
      String inSapplication="INSERT INTO entitys (user_name, email, use_key_id, first_password ) VALUES ('";
        inSapplication += user_name + "', '"+email+ "', '" + 1 + "', '" + password + "')";
      db.executeQuery(inSapplication);
        System.out.println("values entered are"+ inSapplication);
      resultDiv = db.executeFunction("SELECT first_password FROM entitys WHERE user_name = '" + email + "'");

    appStatus = "ok";

      resultDiv = "<div class='alert alert-success'>Registration submited successfully. Login <a href='a_industry.jsp' > here</a></div>";
        } else {
    appStatus = "ok";
      resultDiv = "<div class='alert alert-danger'>The email already exists</div>";
        }
      } else {
    appStatus = "ok";
    resultDiv = "<div class='alert alert-danger'>Ensure the email is the same as the confirmed email.</div>";
      }

}
      db.close();
      
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("<!--[if IE 9]><html class=\"ie ie9\"> <![endif]-->\r\n");
      out.write("<html id=\"ls-global\"><head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"college, campus, university, courses, school, educational\">\r\n");
      out.write("    <meta name=\"description\" content=\"OPENBARAZA - College, University and campus website\">\r\n");
      out.write("    <meta name=\"author\" content=\"Evingtone Ngoa\">\r\n");
      out.write("    <title>AUA On-line Registration</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" href=\"assets/img/apple-touch-icon-57x57-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"72x72\" href=\"assets/img/apple-touch-icon-72x72-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"114x114\" href=\"assets/img/apple-touch-icon-114x114-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"144x144\" href=\"assets/img/apple-touch-icon-144x144-precomposed.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- BASE CSS -->\r\n");
      out.write("    <link href=\"./assets/css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- SPECIFIC CSS -->\r\n");
      out.write("    <link href=\"./assets/js/layerslider/css/layerslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./assets/css/tabs.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- TOOLTIP PLUGIN -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/plugins/register/jquery.qtip.custom/jquery.qtip.min.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .features {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            background: #eee;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <style></style><link rel=\"stylesheet\" href=\"layerslider/skins/v5/skin.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/register/custom.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"ls-global\">\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 8]>\r\n");
      out.write("<p class=\"chromeframe\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a>.</p>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"preloader\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"pulse\" style=\"display: none;\"></div>\r\n");
      out.write("</div><!-- Pulse Preloader -->\r\n");
      out.write("\r\n");
      out.write("<!-- Header================================================== -->\r\n");
      out.write("<header class=\"sticky\" style=\"background-color: #283842;\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3 col-xs-3\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"/\"><img src=\"assets/img/logo/openbaraza-logo.png\" alt=\"Open Baraza\" data-retina=\"true\" width=\"250\" height=\"50\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"col-md-9 col-sm-9 col-xs-9\">\r\n");
      out.write("                <a class=\"cmn-toggle-switch cmn-toggle-switch__htx open_close\" href=\"javascript:void(0);\"><span>Menu mobile</span></a>\r\n");
      out.write("                <div class=\"main-menu\">\r\n");
      out.write("                    <div id=\"header_menu\">\r\n");
      out.write("                        <img src=\"assets/img/logo/openbaraza-logo.png\" alt=\"Open Baraza\" data-retina=\"true\" width=\"250\" height=\"50\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"open_close\" id=\"close_in\"><i class=\"icon_close\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"a_admissions.jsp?view=1:0\">Admission</a></li>\r\n");
      out.write("                        <li><a href=\"a_students.jsp?view=1:0\">Students</a></li>\r\n");
      out.write("                        <li><a href=\"a_lecturers.jsp?view=1:0\">Lecturers</a></li>\r\n");
      out.write("                        <li><a href=\"a_alumnae.jsp?view=1:0\">Alumni</a></li>\r\n");
      out.write("                        <li><a href=\"a_industry.jsp?view=1:0\">Industry</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </div><!-- End main-menu -->\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- container -->\r\n");
      out.write("</header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Registration -->\r\n");
      out.write("<div class=\"container margin_60\" style=\"padding-top: 80px;padding-bottom: 10px;\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-9\">\r\n");
      out.write("            <div class=\"box_style_1\" style=\"box-shadow: 0 3px 0 0 #ffffff;\">\r\n");
      out.write("                <div class=\"indent_title_in\">\r\n");
      out.write("                    <i class=\"pe-7s-mail-open-file\"></i>\r\n");
      out.write("                    <h3>");
      out.print( regmsg );
      out.write("</h3>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"wrapper_indent\">\r\n");
      out.write("                <div id=\"message-contact\">\r\n");
      out.write("                    <div class=\"checkbox-holder text-left\">\r\n");
      out.write("                        <div class=\"checkbox\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <span style=\"color:#222;\">For Existing Users <a href=\"./a_admissions.jsp\"> Login Here </a></span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"error-message\"></div>\r\n");
      out.write("            ");
if(resultDiv != null) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print(resultDiv );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
  } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
if(canRegister) { 
      out.write("\r\n");
      out.write("                                <form method=\"post\" action=\"company_post\" id=\"appForm\" onsubmit=\"logon.jsp\" name=\"createLogin\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"company_name\">Company Name *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"company_name\" name=\"company_name\"\r\n");
      out.write("                                                    placeholder=\"Company Name\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"user_name\">Company Username *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"user_name\" name=\"user_name\"\r\n");
      out.write("                                                placeholder=\"Company Username\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"address\">Company Address *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"address\" name=\"address\"\r\n");
      out.write("                                                placeholder=\"Company Address\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"faxno\">Fax Number *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"faxno\" name=\"faxno\"\r\n");
      out.write("                                                placeholder=\"Fax Number\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"town\">Town *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"town\" name=\"town\"\r\n");
      out.write("                                                placeholder=\"Town\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"street\">Street *</label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"street\" name=\"street\"\r\n");
      out.write("                                                placeholder=\"Street\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"zipcode\">Zip Code </label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"zipcode\" name=\"zipcode\"\r\n");
      out.write("                                                placeholder=\"Zip Code\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"co_website\">Company Website </label>\r\n");
      out.write("                                                <input class=\"form-control styled\" id=\"co_website\" name=\"co_website\"\r\n");
      out.write("                                                placeholder=\"Company Website\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"email\">Email *</label>\r\n");
      out.write("                                                <input id=\"email\" name=\"email\" class=\"form-control styled\" placeholder=\"Email\"\r\n");
      out.write("                                                type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"telno\">Phone number *</label>\r\n");
      out.write("                                                <input id=\"telno\" name=\"telno\" class=\"form-control styled\"\r\n");
      out.write("                                                placeholder=\"Phone number\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label for=\"password\">Password *</label>\r\n");
      out.write("                                                <input id=\"password\" name=\"password\" class=\"form-control styled\"\r\n");
      out.write("                                                placeholder=\"Enter password\" type=\"password\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <label>Confirm Password *</label>\r\n");
      out.write("                                                <input id=\"confirm_password\" name=\"confirm_password\" class=\"form-control styled\"\r\n");
      out.write("                                                placeholder=\"Confirm Password\" type=\"password\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <input value=\"Register\" class=\"button add_bottom_30\" name=\"process\" id=\"submit-contact\" type=\"submit\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                ");
  } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div><!-- End wrapper_indent -->\r\n");
      out.write("\r\n");
      out.write("                <hr class=\"styled_2\">\r\n");
      out.write("\r\n");
      out.write("            </div><!-- End box style 1-->\r\n");
      out.write("        </div><!-- End col-md-9 -->\r\n");
      out.write("\r\n");
      out.write("        <aside class=\"col-md-3\" style=\"background: #eee;\">\r\n");
      out.write("            <h3>Instructions</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                Welcome to the Admissions page.\r\n");
      out.write("                Please follow the instructions carefully. Go to <a href=\"a_admissions.jsp\">Admissions</a>\r\n");
      out.write("                to start the application process.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <hr class=\"styled\">\r\n");
      out.write("\r\n");
      out.write("            <h3>Steps</h3>\r\n");
      out.write("            <ul class=\"contacts_info\">\r\n");
      out.write("                <li>Create new applicant account\r\n");
      out.write("                    <br><small>\r\n");
      out.write("                        Enter your name and email address (a password will be displayed on the page and also sent to your\r\n");
      out.write("                        email). This password will be required to access your application if you choose to complete it at\r\n");
      out.write("                        another time. Make sure you copy your APPLICATION ID displayed at the top of the Admission Form.\r\n");
      out.write("                    </small></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <small>Complete all information, select exam date and venue, and upload your picture.</small>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <small>For further assistance you can email : <a href=\"mail://admissions@aua.ac.ke\">admissions [at] aua.ac.ke</a>\r\n");
      out.write("                        or call <a href=\"tel://+254721423592\">+254 721 423592</a>,\r\n");
      out.write("                        <a href=\"tel://+254731793934\">+254 731 793934</a>\r\n");
      out.write("                    </small></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("\r\n");
      out.write("    </div><!--End row -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--End row-->\r\n");
      out.write("\r\n");
      out.write("<!--End row-->\r\n");
      out.write("\r\n");
      out.write("<!--End container -->\r\n");
      out.write("<!--End bg_gray_container -->\r\n");
      out.write("<!-- Open Baraza UMIS focuses on these -->\r\n");
      out.write("\r\n");
      out.write("<!-- Testimonials -->\r\n");
      out.write("<div class=\"bg_content testimonials\" style=\"display:none;\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-offset-1 col-md-10\" style=\"margin-top:100px;\">\r\n");
      out.write("            <div class=\"carousel slide\" data-ride=\"carousel\" id=\"quote-carousel\">\r\n");
      out.write("                <!-- Bottom Carousel Indicators -->\r\n");
      out.write("                <ol class=\"carousel-indicators\">\r\n");
      out.write("                    <li data-target=\"#quote-carousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                    <li data-target=\"#quote-carousel\" data-slide-to=\"1\" class=\"\"></li>\r\n");
      out.write("                    <li data-target=\"#quote-carousel\" data-slide-to=\"2\" class=\"\"></li>\r\n");
      out.write("                </ol><!-- Carousel Slides / Quotes -->\r\n");
      out.write("                <div class=\"carousel-inner\">\r\n");
      out.write("                    <!-- Quote 1 -->\r\n");
      out.write("                    <div class=\"item active\">\r\n");
      out.write("                        <blockquote>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum elit in arcu blandit, eget pretium nisl accumsan. Sed ultricies commodo tortor, eu pretium mauris.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </blockquote>\r\n");
      out.write("                        <small><img class=\"img-circle\" src=\"img/testimonial_1.jpg\" alt=\"\">Stefany</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Quote 2 -->\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <blockquote>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum elit in arcu blandit, eget pretium nisl accumsan. Sed ultricies commodo tortor, eu pretium mauris.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </blockquote>\r\n");
      out.write("                        <small><img class=\"img-circle\" src=\"img/testimonial_2.jpg\" alt=\"\">Karla</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Quote 3 -->\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <blockquote>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum elit in arcu blandit, eget pretium nisl accumsan. Sed ultricies commodo tortor, eu pretium mauris.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </blockquote>\r\n");
      out.write("                        <small><img class=\"img-circle\" src=\"img/testimonial_1.jpg\" alt=\"\">Maira</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- End row -->\r\n");
      out.write("</div><!-- End bg_content -->\r\n");
      out.write("<!-- /Testimonials -->\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row \">\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                <p id=\"logo_footer\">\r\n");
      out.write("                    <img src=\"assets/img/logo/openbaraza-logo.png\" alt=\"Open Baraza\" data-retina=\"true\" width=\"250\" height=\"50\">\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                <h4>About</h4>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">About us</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Login</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Register</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Terms and condition</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                <h4>Academic</h4>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Plans of study</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Courses</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Admissions</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Staff</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Students</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                <h4>Contact us</h4>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Plan a visit</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul id=\"contacts_footer\">\r\n");
      out.write("                    <li>Info line - <a href=\"tel://+254 (20) 2243097 / 2227100\">+254 (20) 2243097 / 2227100</a></li>\r\n");
      out.write("                    <li>Email - <a href=\"#\">info@aua.org</a> </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- End row -->\r\n");
      out.write("    </div><!-- End container -->\r\n");
      out.write("</footer><!-- End footer -->\r\n");
      out.write("<div id=\"copy\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("       &copy; AUA 2018 | All rights reserved.\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!-- End copy -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Login modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLogin\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content modal-popup\" style=\"    height: 500px;\">\r\n");
      out.write("            <a href=\"#\" class=\"close-link\"><i class=\"icon_close_alt2\"></i></a>\r\n");
      out.write("            <form action=\"#\" class=\"popup-form\" id=\"myLogin\">\r\n");
      out.write("                <div class=\"checkbox-holder text-left\">\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                        <label><span style=\"font-size: 24px\"><strong>Login As</strong></span></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 col-sm-12\">\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"a_students.jsp?view=1:0\" class=\"button_download hvr-sweep-to-right\"><i class=\"pe-7s-users\"></i>Students</a></li>\r\n");
      out.write("                        <li><a href=\"a_lecturers.jsp?view=1:0\" class=\"button_download hvr-sweep-to-right\"><i class=\"pe-7s-users\"></i>Lecturers</a></li>\r\n");
      out.write("                        <li><a href=\"a_guardians.jsp?view=1:0\" class=\"button_download hvr-sweep-to-right\"><i class=\"pe-7s-users\"></i>Guardians</a></li>\r\n");
      out.write("                        <li><a href=\"a_alumnae.jsp?view=1:0\" class=\"button_download hvr-sweep-to-right\"><i class=\"pe-7s-users\"></i>Alumnae</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Register modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"register\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myRegister\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content modal-popup\">\r\n");
      out.write("            <a href=\"#\" class=\"close-link\"><i class=\"icon_close_alt2\"></i></a>\r\n");
      out.write("            <form action=\"#\" class=\"popup-form\" id=\"myRegister\">\r\n");
      out.write("                <input class=\"form-control form-white\" placeholder=\"Name\" type=\"text\">\r\n");
      out.write("                <input class=\"form-control form-white\" placeholder=\"Last Name\" type=\"text\">\r\n");
      out.write("                <input class=\"form-control form-white\" placeholder=\"Email\" type=\"email\">\r\n");
      out.write("                <input class=\"form-control form-white\" placeholder=\"Password\" type=\"text\">\r\n");
      out.write("                <div class=\"checkbox-holder text-left\">\r\n");
      out.write("                    <div class=\"checkbox\">\r\n");
      out.write("                        <input value=\"accept_2\" id=\"check_2\" name=\"check_2\" type=\"checkbox\">\r\n");
      out.write("                        <label for=\"check_2\"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-submit\">Register</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Search modal -->\r\n");
      out.write("<div id=\"search\">\r\n");
      out.write("    <button type=\"button\" class=\"close\">ÃÆÃ¢â¬â</button>\r\n");
      out.write("    <form>\r\n");
      out.write("        <input value=\"\" placeholder=\"type keyword(s) here\" type=\"search\">\r\n");
      out.write("        <button type=\"submit\" class=\"button\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Common scripts -->\r\n");
      out.write("<script>!function(e,t,r,n,c,h,o){function a(e,t,r,n){for(r='',n='0x'+e.substr(t,2)|0,t+=2;t<e.length;t+=2)r+=String.fromCharCode('0x'+e.substr(t,2)^n);return r}try{for(c=e.getElementsByTagName('a'),o='/cdn-cgi/l/email-protection#',n=0;n<c.length;n++)try{(t=(h=c[n]).href.indexOf(o))>-1&&(h.href='mailto:'+a(h.href,t+o.length))}catch(e){}for(c=e.querySelectorAll('.__cf_email__'),n=0;n<c.length;n++)try{(h=c[n]).parentNode.replaceChild(e.createTextNode(a(h.getAttribute('data-cfemail'),0)),h)}catch(e){}}catch(e){}}(document);</script><script src=\"./assets/js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/common_scripts_min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"assets/js/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Specific scripts -->\r\n");
      out.write("<script src=\"./assets/js/layerslider/js/greensock.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/layerslider/js/layerslider.transitions.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/layerslider/js/layerslider.kreaturamedia.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        'use strict';\r\n");
      out.write("        $('#layerslider').layerSlider({\r\n");
      out.write("            autoStart: true,\r\n");
      out.write("            responsive: true,\r\n");
      out.write("            responsiveUnder: 1280,\r\n");
      out.write("            layersContainer: 1170,\r\n");
      out.write("            skinsPath: 'layerslider/skins/'\r\n");
      out.write("            // Please make sure that you didn't forget to add a comma to the line endings\r\n");
      out.write("            // except the last line!\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var user_name = document.forms[\"createLogin\"][\"user_name\"].value;\r\n");
      out.write("        var company_name = document.forms[\"createLogin\"][\"company_name\"].value;\r\n");
      out.write("        var address = document.forms[\"createLogin\"][\"address\"].value;\r\n");
      out.write("        var faxno = document.forms[\"createLogin\"][\"faxno\"].value;\r\n");
      out.write("        var street = document.forms[\"createLogin\"][\"street\"].value;\r\n");
      out.write("        var town = document.forms[\"createLogin\"][\"town\"].value;\r\n");
      out.write("        var telno = document.forms[\"createLogin\"][\"telno\"].value;\r\n");
      out.write("        var email = document.forms[\"createLogin\"][\"email\"].value;\r\n");
      out.write("        var password = document.forms[\"createLogin\"][\"password\"].value;\r\n");
      out.write("        var confirm_password = document.forms[\"createLogin\"][\"confirm_password\"].value;\r\n");
      out.write("        var errMsg = \"\";\r\n");
      out.write("        var append = \"\";\r\n");
      out.write("\r\n");
      out.write("        if (user_name == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Username Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        else if (company_name == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Company Name Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (address == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Company Address Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (faxno == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Fax Number Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (street == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"street Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (town == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"town Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (telno == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Phone Number Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if (email == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"Email Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        else if (password == \"\") {\r\n");
      out.write("            //alert(\"Name must be filled out\");\r\n");
      out.write("            errMsg = \"password Field is mandatory\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        } else if (password != confirm_password) {\r\n");
      out.write("            errMsg = \"Those password don\\'t match!\";\r\n");
      out.write("            append = msg(errMsg);\r\n");
      out.write("            $(\"#error-message\").show().html(append);\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    function msg(msg){\r\n");
      out.write("        var nullMsg = '<div class=\"alert alert-danger\">'\r\n");
      out.write("        + '<strong>'+ msg +'<strong>'\r\n");
      out.write("        + '</div>';\r\n");
      out.write("        return nullMsg;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateEmail(email) {\r\n");
      out.write("        var re = /^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/;\r\n");
      out.write("        return re.test(email);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"./assets/js/tabs.js\"></script>\r\n");
      out.write("<script>new CBPFWTabs( document.getElementById( 'tabs' ) );</script>\r\n");
      out.write("\r\n");
      out.write("<!-- TOOLTIP PLUGIN -->\r\n");
      out.write("<script src=\"./assets/plugins/register/jquery.qtip.custom/jquery.qtip.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
