/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-08-28 09:48:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import org.baraza.DB.BQuery;
import org.baraza.web.*;
import org.baraza.xml.BElement;
import com.dewcis.StudentsDashboard;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1550740869000L));
    _jspx_dependants.put("jar:file:/opt/projects/tomcat/webapps/aua/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064323020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.baraza.web");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.baraza.xml.BElement");
    _jspx_imports_classes.add("org.baraza.DB.BQuery");
    _jspx_imports_classes.add("com.dewcis.StudentsDashboard");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.6\n");
      out.write("Version: 4.5.4\n");
      out.write("Author: KeenThemes\n");
      out.write("Website: http://www.keenthemes.com/\n");
      out.write("Contact: support@keenthemes.com\n");
      out.write("Follow: www.twitter.com/keenthemes\n");
      out.write("Like: www.facebook.com/keenthemes\n");
      out.write("Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes\n");
      out.write("License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.\n");
      out.write("-->\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\n");
      out.write("<!--[if !IE]><!-->\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <!--<![endif]-->\n");
      out.write("    <!-- BEGIN HEAD -->\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <title>Metronic | Dashboard 2</title>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\n");
      out.write("        <meta content=\"\" name=\"description\" />\n");
      out.write("        <meta content=\"\" name=\"author\" />\n");
      out.write("        <!-- BEGIN GLOBAL MANDATORY STYLES -->\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\".../aua/assets/global/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/uniform/css/uniform.default.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END GLOBAL MANDATORY STYLES -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL PLUGINS -->\n");
      out.write("        <link href=\"../aua/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/morris/morris.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/fullcalendar/fullcalendar.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/plugins/jqvmap/jqvmap/jqvmap.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("        <!-- BEGIN THEME GLOBAL STYLES -->\n");
      out.write("        <link href=\"../aua/assets/global/css/components-rounded.css\" rel=\"stylesheet\" id=\"style_components\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/global/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END THEME GLOBAL STYLES -->\n");
      out.write("        <!-- BEGIN THEME LAYOUT STYLES -->\n");
      out.write("        <link href=\"../aua/assets/layouts/layout4/css/layout.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"../aua/assets/layouts/layout4/css/themes/light.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\" />\n");
      out.write("        <link href=\"../aua/assets/layouts/layout4/css/custom.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END THEME LAYOUT STYLES -->\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\" /> </head>\n");
      out.write("    <!-- END HEAD -->\n");
      out.write("\n");
      out.write("    <body class=\"page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo\">\n");
      out.write("       \n");
      out.write("        <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6 col-sm-6\">\n");
      out.write("                            <div class=\"portlet light bordered\">\n");
      out.write("                                <div class=\"portlet-title\">\n");
      out.write("                                    <div class=\"caption caption-md\">\n");
      out.write("                                        <i class=\"icon-bar-chart font-red\"></i>\n");
      out.write("                                        <span class=\"caption-subject font-red bold uppercase\">Track your registration Approvals</span>\n");
      out.write("                                    \n");
      out.write("                                    </div>\n");
      out.write("                               \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"portlet-body\">\n");
      out.write("                                    <div class=\"row number-stats margin-bottom-30\">\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6 col-xs-6\">\n");
      out.write("                                            <div class=\"stat-left\">\n");
      out.write("                                                <div class=\"stat-chart\">\n");
      out.write("                                                    <! do not line break \"sparkline_bar\" div. sparkline chart has an issue when the container div has line break >\n");
      out.write("                                                    <div id=\"sparkline_bar\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"stat-number\">\n");
      out.write("                                                    <div class=\"title\"> Approved </div>\n");
      out.write("                                                    <div class=\"number\" id = \"approved\">0</div>\n");
      out.write("                                                </div>\n");
      out.write("                              \n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-6 col-sm-6 col-xs-6\">\n");
      out.write("                                            <div class=\"stat-right\">\n");
      out.write("                                                <div class=\"stat-chart\">\n");
      out.write("                                                    <! do not line break \"sparkline_bar\" div. sparkline chart has an issue when the container div has line break >\n");
      out.write("                                                    <div id=\"sparkline_bar2\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"stat-number\">\n");
      out.write("                                                    <div class=\"title\"> Pending </div>\n");
      out.write("                                                    <div class=\"number\" id = \"unapproved\">0</div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"table-scrollable table-scrollable-borderless\">\n");
      out.write("                                        <table id= \"myTable\" class=\"table table-hover table-light\">           \n");
      out.write("      \n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                   \n");
      out.write("                    </div>        \n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("<script src=\"../aua/assets/global/plugins/respond.min.js\"></script>\n");
      out.write("<script src=\"../aua/assets/global/plugins/excanvas.min.js\"></script> \n");
      out.write("<![endif]\n");
      out.write("-->\n");
      out.write("\n");
      out.write("        <!-- BEGIN CORE PLUGINS -->\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/js.cookie.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jquery.blockui.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/uniform/jquery.uniform.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END CORE PLUGINS -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL PLUGINS -->\n");
      out.write("        <script src=\"../aua/assets/global/plugins/moment.min.js\" type=\"text/javascript\"></script>\n");
      out.write("       <!--  <script src=\"../aua/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/morris/morris.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/morris/raphael-min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/counterup/jquery.waypoints.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/counterup/jquery.counterup.min.js\" type=\"text/javascript\"></script> -->\n");
      out.write("        <!-- <script src=\"../aua/assets/global/plugins/amcharts/amcharts/amcharts.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/serial.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/pie.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/radar.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/themes/light.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/themes/patterns.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amcharts/themes/chalk.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/ammap/ammap.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/ammap/maps/js/worldLow.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/amcharts/amstockcharts/amstock.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/fullcalendar/fullcalendar.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/flot/jquery.flot.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/flot/jquery.flot.resize.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/flot/jquery.flot.categories.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js\" type=\"text/javascript\"></script> -->\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jquery.sparkline.min.js\" type=\"text/javascript\"></script>\n");
      out.write("       <!--  <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js\" type=\"text/javascript\"></ --><!-- script> -->\n");
      out.write("        <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("        <!-- BEGIN THEME GLOBAL SCRIPTS -->\n");
      out.write("        <script src=\"../aua/assets/global/scripts/app.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END THEME GLOBAL SCRIPTS -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL SCRIPTS -->\n");
      out.write("        <script src=\"../aua/assets/pages/scripts/dashboard.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END PAGE LEVEL SCRIPTS -->\n");
      out.write("        <!-- BEGIN THEME LAYOUT SCRIPTS -->\n");
      out.write("       <!--  <script src=\"../aua/assets/layouts/layout4/scripts/layout.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/layouts/layout4/scripts/demo.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../aua/assets/layouts/global/scripts/quick-sidebar.min.js\" type=\"text/javascript\"></script> -->\n");
      out.write("        <!-- END THEME LAYOUT SCRIPTS -->\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t\n");
      out.write("$(document).ready(function(){\n");
      out.write("  $.ajax({\n");
      out.write("   url:\"./dashboard\",\n");
      out.write("   method:\"GET\",\n");
      out.write("   dataType:\"json\",\n");
      out.write("   success:function(data){\n");
      out.write("   \tvar approve = 0;\n");
      out.write("   \tvar un_approved = -1;\n");
      out.write("   \tfor(var i = 0; i<data.length; i++ ){\n");
      out.write("   \t\tvar ict_approval =\tdata[i].ict_approval;\n");
      out.write("   \t\tvar overload_approval = data[i].overload_approval;\n");
      out.write("   \t\tvar finance_approval = data[i].finance_approval;\n");
      out.write("   \t\tvar residence_approval = data[i].residence_approval;\n");
      out.write("   \t\tvar student_dean_approval = data[i].student_dean_approval;\n");
      out.write("   \t\tvar registrar_approval = data[i].registrar_approval;\n");
      out.write("   \t\tvar student_affairs_approval = data[i].student_affairs_approval;\n");
      out.write("\n");
      out.write("   \t\tfor (rec in data[i]){\n");
      out.write("   \t\t\tconsole.log(\"============>\"+data[i][rec]);\n");
      out.write("   \t\t\tif(data[i][rec]=='Approved'){\n");
      out.write("   \t\t\t\tapprove = approve+1;\n");
      out.write("   \t\t\t}\n");
      out.write("   \t\t\telse{\n");
      out.write("   \t\t\t\tun_approved = un_approved+1;\n");
      out.write("   \t\t\t}\n");
      out.write("   \t}\n");
      out.write("   \tconsole.log(\"====================Approved\"+approve);\n");
      out.write("   \tconsole.log(\"====================unApproved\"+un_approved);\n");
      out.write("   \t\t$(\"#approved\").text(approve);\n");
      out.write("   \t\t$(\"#unapproved\").text(un_approved);\n");
      out.write("\n");
      out.write("   \t\tvar tableRef = document.getElementById('myTable');\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar ict  = document.createTextNode(ict_approval);\n");
      out.write("  \t\tnewCell.appendChild(ict);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar ict_text  = document.createTextNode(\"ICT Approval\");\n");
      out.write("  \t\tnewCell.appendChild(ict_text);\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar finance  = document.createTextNode(finance_approval);\n");
      out.write("  \t\tnewCell.appendChild(finance);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar finance_text  = document.createTextNode(\"finance Approval\");\n");
      out.write("  \t\tnewCell.appendChild(finance_text);\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar residence  = document.createTextNode(residence_approval);\n");
      out.write("  \t\tnewCell.appendChild(residence);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar residence_text  = document.createTextNode(\"Residence Approval\");\n");
      out.write("  \t\tnewCell.appendChild(residence_text);\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar overload  = document.createTextNode(overload_approval);\n");
      out.write("  \t\tnewCell.appendChild(overload);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar overload_text  = document.createTextNode(\"Overload Approval\");\n");
      out.write("  \t\tnewCell.appendChild(overload_text);\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar dean  = document.createTextNode(student_dean_approval);\n");
      out.write("  \t\tnewCell.appendChild(dean);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar dean_text  = document.createTextNode(\"Student Dean Approval\");\n");
      out.write("  \t\tnewCell.appendChild(dean_text);\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar registrar  = document.createTextNode(registrar_approval);\n");
      out.write("  \t\tnewCell.appendChild(registrar);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar registrar_text  = document.createTextNode(\"Registrar Approval\");\n");
      out.write("  \t\tnewCell.appendChild(registrar_text);\n");
      out.write("\n");
      out.write("  \t\tvar newRow   = tableRef.insertRow(tableRef.rows.length);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar studentaffairs  = document.createTextNode(student_affairs_approval);\n");
      out.write("  \t\tnewCell.appendChild(studentaffairs);\n");
      out.write("  \t\tvar newCell  = newRow.insertCell(0);\n");
      out.write("  \t\tvar students_text  = document.createTextNode(\"Student Affairs Approval\");\n");
      out.write("  \t\tnewCell.appendChild(students_text);\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   \t\tconsole.log(\"This \"+ JSON.stringify(data[i]));\n");
      out.write("   \t}\n");
      out.write("   \t\n");
      out.write("   \t\n");
      out.write("   }\n");
      out.write("  })\n");
      out.write(" });\n");
      out.write(" \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /dashboard.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /dashboard.jsp(2,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /dashboard.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("mainPage");
      // /dashboard.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue("a_guardians.jsp");
      // /dashboard.jsp(3,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setScope("page");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
