/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-09-23 13:31:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class staff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"college, campus, university, courses, school, educational\">\r\n");
      out.write("    <meta name=\"description\" content=\"OPENBARAZA - College, University and campus website\">\r\n");
      out.write("    <meta name=\"author\" content=\"Evingtone Ngoa\">\r\n");
      out.write("    <title>AUA - Staff</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./assets/img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"assets/img/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\" />\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"72x72\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"114x114\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"144x144\" href=\"./assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- BASE CSS -->\r\n");
      out.write("    <link href=\"./assets/css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- YOUR CUSTOM CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/register/custom.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"preloader\">\r\n");
      out.write("\t<div class=\"pulse\"></div>\r\n");
      out.write("</div><!-- Pulse Preloader -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header================================================== -->\r\n");
      out.write("    <header>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3 col-sm-3 col-xs-3\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"index.html\"><img src=\"assets/img/logo/openbaraza-logo.png\" width=\"250\" height=\"50\" alt=\"AUA\" data-retina=\"true\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"col-md-9 col-sm-9 col-xs-9\">\r\n");
      out.write("            <a class=\"cmn-toggle-switch cmn-toggle-switch__htx open_close\" href=\"javascript:void(0);\"><span>Menu mobile</span></a>\r\n");
      out.write("            \r\n");
      out.write("            </div><!-- End main-menu -->\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- container -->\r\n");
      out.write("    </header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"sub_header bg_2\" style=\"height: 20%\">\r\n");
      out.write("        \t<div id=\"intro_txt\">\r\n");
      out.write("\t\t\t<h1>Staff <strong>Portal</strong> </h1>\r\n");
      out.write("            <p>Use the Links to Login To your Respective Interface</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div> <!--End sub_header -->\r\n");
      out.write(" \r\n");
      out.write(" \t\t<div class=\"container_gray_bg\" style=\"background-color: #b9b9b9\">\r\n");
      out.write("        <div class=\"container margin_60\">\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("        \t<div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./registry\">\r\n");
      out.write("                <i class=\"pe-7s-user\"></i>\r\n");
      out.write("            \t<h3>Registry</h3>\r\n");
      out.write("           </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./a_lecturers.jsp?view=1:0\">\r\n");
      out.write("                <i class=\"pe-7s-user-female\"></i>\r\n");
      out.write("            \t<h3>Lecturer</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./c_finance.jsp\">\r\n");
      out.write("                <i class=\"pe-7s-cash\"></i>\r\n");
      out.write("            \t<h3>Finance</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div><!--End row-->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./hospitality\">\r\n");
      out.write("                <i class=\"pe-7s-home\"></i>\r\n");
      out.write("            \t<h3>Hospitality</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./ict\">\r\n");
      out.write("                <i class=\"pe-7s-network\"></i>\r\n");
      out.write("            \t<h3>ICT</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("            \t<a class=\"box_feat\" href=\"./school\">\r\n");
      out.write("                <i class=\"pe-7s-airplay\"></i>\r\n");
      out.write("            \t<h3>School</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div><!--End row-->\r\n");
      out.write("    \r\n");
      out.write("        </div><!--End container -->\r\n");
      out.write("        </div><!--End bg_gray_container -->\r\n");
      out.write("        \r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row \">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                        <p id=\"logo_footer\">\r\n");
      out.write("                            <img src=\"assets/img/logo/openbaraza-logo.png\" alt=\"Open Baraza\" data-retina=\"true\" width=\"250\"\r\n");
      out.write("                                height=\"50\">\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                        <h4>About</h4>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">About us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Login</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Register</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Terms and condition</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                        <h4>Academic</h4>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Plans of study</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Courses</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Admissions</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Staff</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Students</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-3\">\r\n");
      out.write("                        <h4>Contact us</h4>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Plan a visit</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul id=\"contacts_footer\">\r\n");
      out.write("                            <li>Info line - <a href=\"tel://+254 (20) 2243097 / 2227100\">+254 (20) 2243097 / 2227100</li>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>Email - <a href=\"#\">info@aua.org</a> </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- End row -->\r\n");
      out.write("            </div><!-- End container -->\r\n");
      out.write("        </footer><!-- End footer -->\r\n");
      out.write("        <div id=\"copy\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                 Â© Atena 2015 - All rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- End copy -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- Login modal -->   \r\n");
      out.write("<div class=\"modal fade\" id=\"login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLogin\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content modal-popup\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"close-link\"><i class=\"icon_close_alt2\"></i></a>\r\n");
      out.write("\t\t\t\t<form action=\"#\" class=\"popup-form\" id=\"myLogin\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Username\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t<div class=\"checkbox-holder text-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" value=\"accept_1\" id=\"check_1\" name=\"check_1\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"check_1\"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-submit\">Submit</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("    \r\n");
      out.write("<!-- Register modal -->   \r\n");
      out.write("<div class=\"modal fade\" id=\"register\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myRegister\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content modal-popup\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"close-link\"><i class=\"icon_close_alt2\"></i></a>\r\n");
      out.write("\t\t\t\t<form action=\"#\" class=\"popup-form\" id=\"myRegister\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control form-white\" placeholder=\"Last Name\">\r\n");
      out.write("                    <input type=\"email\" class=\"form-control form-white\" placeholder=\"Email\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control form-white\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t<div class=\"checkbox-holder text-left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" value=\"accept_2\" id=\"check_2\" name=\"check_2\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"check_2\"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-submit\">Register</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("<!-- Search modal -->   \r\n");
      out.write("<div id=\"search\">\r\n");
      out.write("    <button type=\"button\" class=\"close\">Ã</button>\r\n");
      out.write("    <form>\r\n");
      out.write("        <input type=\"search\" value=\"\" placeholder=\"type keyword(s) here\" >\r\n");
      out.write("        <button type=\"submit\" class=\"button\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Common scripts -->\r\n");
      out.write("<script src=\"./assets/js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/common_scripts_min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
