/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-08-28 09:23:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/./assets/includes/admin/header.jsp", Long.valueOf(1501854435000L));
    _jspx_dependants.put("/./assets/includes/admin/./styles.jsp", Long.valueOf(1509347679000L));
    _jspx_dependants.put("/./assets/includes/admin/footer.jsp", Long.valueOf(1501835370000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1201570774000L));
    _jspx_dependants.put("/./assets/includes/admin/top_nav_menu.jsp", Long.valueOf(1509716705000L));
    _jspx_dependants.put("jar:file:/opt/projects/tomcat/webapps/hotel/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064323020000L));
    _jspx_dependants.put("/./assets/includes/admin/scripts.jsp", Long.valueOf(1509436057000L));
    _jspx_dependants.put("/./assets/includes/admin/dashboard-navigation.jsp", Long.valueOf(1509961067000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    ");
      out.write("<!DOCTYPE html>\n");
      out.write("    <!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\n");
      out.write("    <!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\n");
      out.write("    <!--[if !IE]><!-->\n");
      out.write("    \n");
      out.write("    <html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("    <meta charset=\"utf-8\"/>\n");
      out.write("    <title>Baraza Hotels | Admin</title>\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\n");
      out.write("    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\n");
      out.write("    <meta content=\"A Baraza hotel system\" name=\"description\"/>\n");
      out.write("    <meta content=\"Evingtone Ngoa | Haron Korir\" name=\"author\"/>\n");
      out.write("    ");
      out.write("    <!-- BEGIN GLOBAL MANDATORY STYLES -->\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"./assets/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"./assets/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"./assets/vendor/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"./assets/vendor/uniform/dist/css/default.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"./assets/vendor/bootstrap-switch/dist/css/bootstrap2/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <!-- END GLOBAL MANDATORY STYLES -->\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/select2/dist/css/select2.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/admin-backend/js/datatables/extensions/Scroller/css/dataTables.scroller.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/admin-backend/js/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/admin-backend/js/datatables/plugins/bootstrap/dataTables.bootstrap.css\"/>\n");
      out.write("        <link href=\"./assets/admin-backend/js/datatables/plugins/bootstrap/dataTables.bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("        <!-- BEGIN PAGE LEVEL MMODAL -->\n");
      out.write("        <link href=\"./assets/admin-backend/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"./assets/admin-backend/plugins/bootstrap-modal/css/bootstrap-modal.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/intl-tel-input/build/css/intlTelInput.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- BEGIN THEME STYLES -->\n");
      out.write("        <link href=\"./assets/admin-backend/css/components-rounded.css\" id=\"style_components\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"./assets/admin-backend/css/plugins.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"./assets/admin-backend/css/layout.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link id=\"style_color\" href=\"./assets/admin-backend/css/themes/light.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"./assets/admin-backend/css/news.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/form-align.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/hotel-custom.css\">\n");
      out.write("        <link href=\"./assets/admin-backend/css/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <!-- END THEME STYLES -->\n");
      out.write("\n");
      out.write('\n');
      out.write("\n");
      out.write("</head>\n");
      out.write("    <body class=\"page-header-fixed page-sidebar-closed-hide-logo\">\n");
      out.write("\n");
      out.write("        ");
      out.write("    <!-- BEGIN HEADER -->\n");
      out.write("    <div class=\"page-header navbar navbar-fixed-top\" style=\"background-color:#00aef0;\">\n");
      out.write("        <!-- BEGIN HEADER INNER -->\n");
      out.write("        <div class=\"page-header-inner\">\n");
      out.write("        <!-- BEGIN LOGO -->\n");
      out.write("        <div class=\"page-logo\">\n");
      out.write("        <a href=\"./\">\n");
      out.write("        <img src=\"./assets/admin-backend/img/logo/nakawa-logo.png\" alt=\"logo\" class=\"logo-default\"/>\n");
      out.write("        </a>\n");
      out.write("        <div class=\"menu-toggler sidebar-toggler\">\n");
      out.write("        <!-- DOC: Remove the above \"hide\" to enable the sidebar toggler button on header -->\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- END LOGO -->\n");
      out.write("        <!-- BEGIN RESPONSIVE MENU TOGGLER -->\n");
      out.write("        <a href=\"javascript:;\" class=\"menu-toggler responsive-toggler\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("        </a>\n");
      out.write("        <!-- END RESPONSIVE MENU TOGGLER -->\n");
      out.write("        <!-- BEGIN PAGE TOP -->\n");
      out.write("        <div class=\"page-top\">\n");
      out.write("        <!-- BEGIN TOP NAVIGATION MENU -->\n");
      out.write("        <div class=\"top-menu\">\n");
      out.write("        <ul class=\"nav navbar-nav pull-right\">\n");
      out.write("        <li class=\"separator hide\">\n");
      out.write("        </li>\n");
      out.write("        <!-- BEGIN USER LOGIN DROPDOWN -->\n");
      out.write("        <!-- DOC: Apply \"dropdown-dark\" class after below \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("        <li class=\"dropdown dropdown-user dropdown-dark\">\n");
      out.write("        <a href=\"javascript:;\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-close-others=\"true\">\n");
      out.write("        <span class=\"username username-hide-on-mobile\" style=\"color: #fff;\">\n");
      out.write("        ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(" </span>\n");
      out.write("        <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->\n");
      out.write("        <img alt=\"\" class=\"img-circle\" src=\"./assets/admin-backend/img/avatar.png\"/>\n");
      out.write("        </a>\n");
      out.write("        <ul class=\"dropdown-menu dropdown-menu-default\">\n");
      out.write("        <li>\n");
      out.write("        <a href=\"profile\">\n");
      out.write("        <i class=\"icon-user\"></i> My Profile </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"divider\"></li>\n");
      out.write("        <li>\n");
      out.write("        <a href=\"./index.jsp?view=83:0\">\n");
      out.write("        <i class=\"icon-rocket\"></i> My Tasks <span class=\"badge badge-success\">\n");
      out.write("        7 </span>\n");
      out.write("        </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"divider\"></li>\n");
      out.write("        <li>\n");
      out.write("        <a data-toggle=\"modal\" href=\"#basic\">\n");
      out.write("        <i class=\"icon-rocket\"></i> Change Password\n");
      out.write("        </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"divider\"></li>\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        </li>\n");
      out.write("        <!-- END USER LOGIN DROPDOWN -->\n");
      out.write("        </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- END TOP NAVIGATION MENU -->\n");
      out.write("        </div>\n");
      out.write("        <!-- END PAGE TOP -->\n");
      out.write("        </div>\n");
      out.write("        <!-- END HEADER INNER -->\n");
      out.write("        </div>\n");
      out.write("    <!-- END HEADER -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"clearfix\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"page-container\">\n");
      out.write("\n");
      out.write("        ");
      out.write("    <!-- BEGIN SIDEBAR -->\n");
      out.write("        <div class=\"page-sidebar-wrapper\">\n");
      out.write("        <!-- DOC: Set data-auto-scroll=\"false\" to disable the sidebar from auto scrolling/focusing -->\n");
      out.write("        <!-- DOC: Change data-auto-speed=\"200\" to adjust the sub menu slide up/down speed -->\n");
      out.write("            <div class=\"page-sidebar navbar-collapse collapse\">\n");
      out.write("            <!-- BEGIN SIDEBAR MENU -->\n");
      out.write("            <!-- DOC: Apply \"page-sidebar-menu-light\" class right after \"page-sidebar-menu\" to enable light sidebar menu style(without borders) -->\n");
      out.write("            <!-- DOC: Apply \"page-sidebar-menu-hover-submenu\" class right after \"page-sidebar-menu\" to enable hoverable(hover vs accordion) sub menu mode -->\n");
      out.write("            <!-- DOC: Apply \"page-sidebar-menu-closed\" class right after \"page-sidebar-menu\" to collapse(\"page-sidebar-closed\" class must be applied to the body element) the sidebar sub menu mode -->\n");
      out.write("            <!-- DOC: Set data-auto-scroll=\"false\" to disable the sidebar from auto scrolling/focusing -->\n");
      out.write("            <!-- DOC: Set data-keep-expand=\"true\" to keep the submenues expanded -->\n");
      out.write("            <!-- DOC: Set data-auto-speed=\"200\" to adjust the sub menu slide up/down speed -->\n");
      out.write("                <ul class=\"page-sidebar-menu \" data-keep-expanded=\"false\" data-auto-scroll=\"true\" data-slide-speed=\"200\">\n");
      out.write("                    <li class=\"start \">\n");
      out.write("                        <a href=\"./dashboard.jsp\">\n");
      out.write("                            <i class=\"icon-home\"></i>\n");
      out.write("                            <span class=\"title\">Dashboard</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"start \">\n");
      out.write("                        <a href=\"reservation?view=bookings:0\">\n");
      out.write("                            <i class=\"icon-drawer\"></i>\n");
      out.write("                            <span class=\"title\">Bookings</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            <!-- END SIDEBAR MENU -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- END SIDEBAR -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"page-content-wrapper\">\n");
      out.write("        <!-- BEGIN CHANGEABLE CONTENT  -->\n");
      out.write("            <div class=\"page-content\">\n");
      out.write("            <!-- STATS -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("\n");
      out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                            <div class=\"dashboard-stat2\" style=\"padding: 15px;\">\n");
      out.write("                                <div class=\"display\" style=\"margin-bottom:0px;\">\n");
      out.write("                                    <div class=\"number\">\n");
      out.write("                                    <h3 class=\"font-green-sharp\"><span id=\"mynewBookings\"></span></h3>\n");
      out.write("                                    <small class=\"font-green-sharp\">MY NEW BOOKINGS</small>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"icon\">\n");
      out.write("                                    <i class=\"font-green-sharp icon-drawer\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </div>\n");
      out.write("            <!-- STATS -->\n");
      out.write("            </div>\n");
      out.write("        <!-- END CHANGEABLE CONTENT -->\n");
      out.write("        ");
      out.write("    <div class=\"page-footer\">\n");
      out.write("        <div class=\"page-footer-inner\">\n");
      out.write("        2015 © Open Baraza. <a href=\"http://dewcis.com\">Dew Cis Solutions Ltd.</a> All Rights Reserved\n");
      out.write("        </div>\n");
      out.write("        <div class=\"scroll-to-top\" style=\"display: block;\">\n");
      out.write("        <i class=\"icon-arrow-up\"></i>\n");
      out.write("        </div>\n");
      out.write("    </div>");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("<!-- BEGIN CORE PLUGINS -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("<script src=\"./assets/admin-backend/js/respond.min.js\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/excanvas.min.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("<script src=\"./assets/admin-backend/js/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/jquery-migrate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->\n");
      out.write("<script src=\"./assets/admin-backend/js/jquery-ui/jquery-ui.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("<script src=\"./assets/vendor/bootstrap/dist/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/vendor/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/jquery.blockui.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/jquery.cokie.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/vendor/uniform/dist/js/jquery.uniform.bundled.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/vendor/bootstrap-switch/dist/js/bootstrap-switch.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<!-- END CORE PLUGINS -->\n");
      out.write("\n");
      out.write("<!-- BEGIN PAGE LEVEL MMODAL -->\n");
      out.write("<script src=\"./assets/admin-backend/plugins/bootstrap-modal/js/bootstrap-modalmanager.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/plugins/bootstrap-modal/js/bootstrap-modal.js\" type=\"text/javascript\"></script>\n");
      out.write("<!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("\n");
      out.write("<script src=\"./assets/admin-backend/js/metronic.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/layout.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"./assets/admin-backend/js/demo.js\" type=\"text/javascript\"></script>\n");
      out.write("<script>\n");
      out.write("jQuery(document).ready(function() {\n");
      out.write("    Metronic.init(); // init metronic core components\n");
      out.write("    Layout.init(); // init current layout\n");
      out.write("    Demo.init(); // init demo features\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<!-- END JAVASCRIPTS -->\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            jQuery(document).ready(function() {\n");
      out.write("\n");
      out.write("                $.post(\"dashboard\", {page: \"dash\"}, function(data){\n");
      out.write("                    $(\"#newBookings\").text(data.new_bookings);\n");
      out.write("                    $(\"#mynewBookings\").text(data.mynew_bookings);\n");
      out.write("                    $(\"#checkIns\").text(data.checkIns);\n");
      out.write("                    $(\"#checkOuts\").text(data.checkOuts);\n");
      out.write("                    $(\"#units\").text(data.available_units);\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <!-- END JAVASCRIPTS -->\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /./assets/includes/admin/top_nav_menu.jsp(31,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /./assets/includes/admin/top_nav_menu.jsp(54,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <li>\n");
          out.write("                <a href=\"auth?tag=logout\">\n");
          out.write("                <i class=\"icon-key\"></i> Log Out </a>\n");
          out.write("            </li>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /./assets/includes/admin/dashboard-navigation.jsp(26,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin.role eq 'ADMINISTRATOR'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <li class=\"start \">\n");
          out.write("                            <a href=\"./calendar.jsp\">\n");
          out.write("                                <i class=\"icon-calendar\"></i>\n");
          out.write("                                <span class=\"title\">Calendar</span>\n");
          out.write("                            </a>\n");
          out.write("                        </li>\n");
          out.write("                        <li class=\"start \">\n");
          out.write("                            <a href=\"javascript:;\">\n");
          out.write("                                <i class=\"icon-doc\"></i>\n");
          out.write("                                <span class=\"title\">Transaction Ledger</span>\n");
          out.write("                            </a>\n");
          out.write("                        </li>\n");
          out.write("                        <li class=\"start \">\n");
          out.write("                            <a href=\"javascript:;\">\n");
          out.write("                                <i class=\"icon-notebook\"></i>\n");
          out.write("                                <span class=\"title\">Journals</span>\n");
          out.write("                            </a>\n");
          out.write("                        </li>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /./assets/includes/admin/dashboard-navigation.jsp(46,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin.role eq 'ADMINISTRATOR' || sessionScope.userLogin.role eq 'SUBSCRIPTION'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <li>\n");
          out.write("                            \n");
          out.write("                            <a href=\"admin.jsp?view=5:0\">\n");
          out.write("                                <i class=\"icon-settings\"></i>\n");
          out.write("                                <span class=\"title\">Administration</span>\n");
          out.write("                                <span class=\"arrow \"></span>\n");
          out.write("                            </a>\n");
          out.write("                            <ul class=\"sub-menu\">\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"admin.jsp?view=5:0\">\n");
          out.write("                                    <i class=\"icon-briefcase\"></i>\n");
          out.write("                                    Organization</a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"admin.jsp?view=35:0\">\n");
          out.write("                                    <i class=\"icon-equalizer\"></i>\n");
          out.write("                                    Hotel Setup</a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-vector \"></i>\n");
          out.write("                                        Departments\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-wallet \"></i>\n");
          out.write("                                        Banks\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-calendar\"></i>\n");
          out.write("                                        Fiscal Years\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-pie-chart \"></i>\n");
          out.write("                                        Chat of accounts\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\" icon-puzzle\"></i>\n");
          out.write("                                        Items\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-envelope-letter \"></i>\n");
          out.write("                                        Emails & News\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-shuffle\"></i>\n");
          out.write("                                        Workflows\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-user-following \"></i>\n");
          out.write("                                        Approvals\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                            </ul>\n");
          out.write("                        </li>\n");
          out.write("                        <li  class=\"last\">\n");
          out.write("                            <a href=\"javascript:;\">\n");
          out.write("                                <i class=\"icon-layers\"></i>\n");
          out.write("                                <span class=\"title\">Reports</span>\n");
          out.write("                                <span class=\"arrow \"></span>\n");
          out.write("                            </a>\n");
          out.write("                            <ul class=\"sub-menu\">\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                        <i class=\"icon-briefcase\"></i>\n");
          out.write("                                        Organization\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                                <li>\n");
          out.write("                                    <a href=\"javascript:;\">\n");
          out.write("                                    <i class=\"icon-equalizer\"></i>\n");
          out.write("                                    Hotel Setup\n");
          out.write("                                    </a>\n");
          out.write("                                </li>\n");
          out.write("                            </ul>\n");
          out.write("                        </li>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /dashboard.jsp(29,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin.role eq 'SUBSCRIPTION' || sessionScope.userLogin.role eq 'ADMINISTRATOR'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
          out.write("                            <div class=\"dashboard-stat2\" style=\"padding: 15px;\">\n");
          out.write("                                <div class=\"display\" style=\"margin-bottom:0px;\">\n");
          out.write("                                    <div class=\"number\">\n");
          out.write("                                    <h3 class=\"font-green-sharp\"><span id=\"newBookings\"></span></h3>\n");
          out.write("                                    <small class=\"font-green-sharp\">NEW BOOKINGS</small>\n");
          out.write("                                    </div>\n");
          out.write("                                    <div class=\"icon\">\n");
          out.write("                                    <i class=\"font-green-sharp icon-drawer\"></i>\n");
          out.write("                                    </div>\n");
          out.write("                                </div>\n");
          out.write("                            </div>\n");
          out.write("                        </div>\n");
          out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
          out.write("                            <div class=\"dashboard-stat2\" style=\"padding: 15px;\">\n");
          out.write("                                <div class=\"display\" style=\"margin-bottom:0px;\">\n");
          out.write("                                    <div class=\"number\">\n");
          out.write("                                    <h3 class=\"font-blue-sharp\"><span id=\"checkIns\"></span></h3>\n");
          out.write("                                    <small class=\"font-blue-sharp\">CHECK-INS TODAY</small>\n");
          out.write("                                    </div>\n");
          out.write("                                    <div class=\"icon\">\n");
          out.write("                                    <i class=\"font-blue-sharp icon-login \"></i>\n");
          out.write("                                    </div>\n");
          out.write("                                </div>\n");
          out.write("                            </div>\n");
          out.write("                        </div>\n");
          out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
          out.write("                            <div class=\"dashboard-stat2\" style=\"padding: 15px;\">\n");
          out.write("                                <div class=\"display\" style=\"margin-bottom:0px;\">\n");
          out.write("                                    <div class=\"number\">\n");
          out.write("                                    <h3 class=\"font-green-sharp\"><span id=\"checkOuts\"></span></h3>\n");
          out.write("                                    <small class=\"font-green-sharp\">CHECK-OUTS TODAY</small>\n");
          out.write("                                    </div>\n");
          out.write("                                    <div class=\"icon\">\n");
          out.write("                                    <i class=\"font-green-sharp  icon-logout\"></i>\n");
          out.write("                                    </div>\n");
          out.write("                                </div>\n");
          out.write("                            </div>\n");
          out.write("                        </div>\n");
          out.write("                        <div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\n");
          out.write("                            <div class=\"dashboard-stat2\" style=\"padding: 15px;\">\n");
          out.write("                                <div class=\"display\" style=\"margin-bottom:0px;\">\n");
          out.write("                                    <div class=\"number\">\n");
          out.write("                                    <h3 class=\"font-blue-sharp\"><span id=\"units\"></span></h3>\n");
          out.write("                                    <small class=\"font-blue-sharp\">UNITS AVAILABLE</small>\n");
          out.write("                                    </div>\n");
          out.write("                                    <div class=\"icon\">\n");
          out.write("                                    <i class=\"font-blue-sharp icon-home\"></i>\n");
          out.write("                                    </div>\n");
          out.write("                                </div>\n");
          out.write("                            </div>\n");
          out.write("                        </div>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
