/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-08-28 09:23:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/./assets/includes/footer.jsp", Long.valueOf(1508153201000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1201570774000L));
    _jspx_dependants.put("/./assets/includes/menu.jsp", Long.valueOf(1510218212000L));
    _jspx_dependants.put("jar:file:/opt/projects/tomcat/webapps/hotel/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1064323020000L));
    _jspx_dependants.put("jar:file:/opt/projects/tomcat/webapps/hotel/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064323020000L));
    _jspx_dependants.put("/./assets/includes/header.jsp", Long.valueOf(1510225310000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
response.addHeader("Cache-Control","no-cache");
      out.write('\n');
response.addHeader("Expires","-1");
      out.write('\n');
response.addHeader("Pragma","no-cache");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <title>Nakawa Hotels</title>\n");
      out.write("        <!--[if IE]>\n");
      out.write("        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>\n");
      out.write("        <![endif]-->\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n");
      out.write("        <meta http-equiv=\"cache-control\" content=\"max-age=1209600,public\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"./assets/img/favicons/apple-icon-57x57.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"./assets/img/favicons/apple-icon-60x60.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"./assets/img/favicons/apple-icon-72x72.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/favicons/apple-icon-76x76.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"./assets/img/favicons/apple-icon-114x114.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"./assets/img/favicons/apple-icon-120x120.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"./assets/img/favicons/apple-icon-144x144.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"./assets/img/favicons/apple-icon-152x152.png\">\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"./assets/img/favicons/apple-icon-180x180.png\">\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"./assets/img/favicons/android-icon-192x192.png\">\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"./assets/img/favicons/favicon-32x32.png\">\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"./assets/img/favicons/favicon-96x96.png\">\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./assets/img/favicons/favicon-16x16.png\">\n");
      out.write("        <link rel=\"manifest\" href=\"./assets/img/favicons/manifest.json\">\n");
      out.write("        <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n");
      out.write("        <meta name=\"msapplication-TileImage\" content=\"./assets/img/favicons/ms-icon-144x144.png\">\n");
      out.write("        <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("\n");
      out.write("        <!--bootstrap-->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("        <!--External Fonts-->\n");
      out.write("        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='https://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='https://fonts.googleapis.com/css?family=Tinos:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("        <!--Plugins-->\n");
      out.write("        <link href='./assets/vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' rel='stylesheet' type='text/css'>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/select2/dist/css/select2.min.css\">\n");
      out.write("        <link href='./assets/vendor/bootstrap-slider/dist/css/bootstrap-slider.min.css' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("        <!--Custom-->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/hotel-custom.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/menu.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/responsive.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/autocomplete.css\">\n");
      out.write("\n");
      out.write("        <!--Fonts-->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/font/font-awesome/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("    /* Always set the map height explicitly to define the size of the div\n");
      out.write("    * element that contains the map. */\n");
      out.write("    #map {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 245px;\n");
      out.write("    }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/intl-tel-input/build/css/intlTelInput.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/font/linea-icon/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/form-align.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/book.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/vendor/simple-line-icons/css/simple-line-icons.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/front-end/responsive.css\">\n");
      out.write("    </head>\n");
      out.write("    <!--MENU-->\n");
      out.write("    ");
      out.write("<div class=\"wrapper\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12 col-sm-12\">\n");
      out.write("            <nav class=\"navbar navbar-default\" style=\"background-color: #00aef0;color: #fff;width:100%;\">\n");
      out.write("                <div class=\"container-fluid centralised\">\n");
      out.write("                    <div class=\"navbar-header\">\n");
      out.write("                        <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("                        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\"\n");
      out.write("                        data-target=\"#nakawa-collapse-mobile\" aria-expanded=\"false\">\n");
      out.write("                            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                        </button>\n");
      out.write("\n");
      out.write("                        <a class=\"navbar-brand\" href=\"./\">\n");
      out.write("                            <i class=\"glyphicon glyphicon-glass\"></i><span class=\"dark-blue\"> Nakawa</span> Hotels\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"nakawa-collapse-mobile\">\n");
      out.write("                    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li class=\"active\"><a href=\"./\">Home</a></li>\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--/MENU-->\n");
      out.write("\n");
      out.write("    <!--CONTENT-->\n");
      out.write("    <div class=\"row centralised central\" style=\"margin-bottom: 20px;\">\n");
      out.write("        <div class=\"col-md-8\" style=\"padding:0px;\">\n");
      out.write("            <!--Register-->\n");
      out.write("            <div class=\"col-md-12 filter-wrapper box-wrapper-shadow min-container\" style=\"padding:0px;position:static;background-color:#fff;z-index:10;margin-top:0px;margin-bottom:20px;\">\n");
      out.write("            <div class=\"title-top-bar\">\n");
      out.write("                <span class=\"title simple-registration-icon\">\n");
      out.write("                    ");
      out.write("\n");
      out.write("                     <span>Register</span>\n");
      out.write("                </span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"padding-form\">\n");
      out.write("                <div class=\"nakawa-date-view-more\">\n");
      out.write("                    <form id=\"frm_register\" method=\"post\" action=\"#\">\n");
      out.write("                        <div class=\"error-message col-md-12 col-xs-12\" id=\"error-message\"></div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\" for=\"first_name\">First Name</label>\n");
      out.write("                            <div class='input-group  nakawa glyphicon glyphicon-user-add' >\n");
      out.write("                                <input type='text' class=\"form-control input-sm\" name=\"first_name\" id=\"first_name\" autocomplete=\"off\" required>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\" for=\"last_name\">Last Name</label>\n");
      out.write("                            <div class='input-group  nakawa glyphicon glyphicon-user-add' >\n");
      out.write("                                <input type='text' class=\"form-control input-sm\" name=\"last_name\" id=\"last_name\" autocomplete=\"off\" required>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\" for=\"password\">Password</label>\n");
      out.write("                            <div class='input-group  nakawa  glyphicon glyphicon-pass' >\n");
      out.write("                                <input type='password' class=\"form-control input-sm\" name=\"password\" id=\"password\" autocomplete=\"off\" required>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group form-groups\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\" for='confirm_password'>Confirm Password</label>\n");
      out.write("                            <div class='input-group  nakawa  glyphicon glyphicon-pass' >\n");
      out.write("                                <input type='password' class=\"form-control input-sm\" name=\"confirm_password\" id=\"confirm_password\" autocomplete=\"off\" required>\n");
      out.write("                                <div id=\"statusMessage\"></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\" for=\"email\">Email</label>\n");
      out.write("                            <div class='input-group  nakawa glyphicon glyphicon-email' >\n");
      out.write("                                <input type='email' class=\"form-control input-sm\" name=\"email\" id=\"email\" autocomplete=\"off\" required>\n");
      out.write("                                <div id=\"emailValidationMessage\"></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-xs-12 form-group\">\n");
      out.write("                            <label class=\"control-label custom-label inputsm\">Phone</label>\n");
      out.write("                            <div class='input-group  nakawa' >\n");
      out.write("                                <input type='tel' class=\"form-control input-sm\" name=\"phone\" id=\"phone\" autocomplete=\"off\" required/>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 col-sm-12\" style=\"margin-bottom:10px;\">\n");
      out.write("                            <div class='input-group' >\n");
      out.write("                                <button id=\"btn_register\" class=\"btn btn-primary\" type=\"button\" name=\"process\" style=\"width:100%\">Register</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <!--Right Sidebar-->\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <!--booking Summary-->\n");
      out.write("            <div class=\"book-sidebar-container book-container-padding\">\n");
      out.write("                <div class=\"book-wrap\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!--/booking Summary-->\n");
      out.write("        </div>\n");
      out.write("        <!--/Right Sidebar-->\n");
      out.write("    </div>\n");
      out.write("    <!--/CONTENT-->\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("    </div> <!--/close container -->\n");
      out.write("    <!--FOOTER-->\n");
      out.write("        <footer class=\"footer row\">\n");
      out.write("            <!--secondary-footer-->\n");
      out.write("            <div class=\"top-footer\">\n");
      out.write("            <div class=\"centralised central \">\n");
      out.write("            <div class=\"col-md-12 col-sm-12\">\n");
      out.write("            <div class=\"footer-address\">\n");
      out.write("            <strong>DewCis Solutions LTD</strong>\n");
      out.write("            12th Floor, Barclays Plaza, Loita Street, Nairobi, Kenya\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-12 col-sm-12\">\n");
      out.write("            <ul class=\"footer-social\">\n");
      out.write("            <li data-toggle=\"tooltip\" title=\"Folow Us On Facebook\">\n");
      out.write("            <a href=\"#\" class=\"footer-social-icon-wrapper\">\n");
      out.write("            <span class=\"footer-icon-wrap\"></span>\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" focusable=\"false\" tabindex=\"-1\" width=\"24\" height=\"24\" viewBox=\"0 0 24\n");
      out.write("            24\"><path class=\"svg-color--primary\" fill=\"#fff\" d=\"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12\n");
      out.write("            2zm3 5.6h-1.5s-.6.3-.6.5v1.6H15c-.1 1.2-.3 2.3-.3 2.3h-1.9v6.8H10V12H8.7V9.7h1.4V7.8c0-.3-.1-2.6 2.9-2.6h2.1c-.1\n");
      out.write("            1-.1 2.1-.1 2.4z\"></path></svg>\n");
      out.write("            <!--Facebook-->\n");
      out.write("            </a>\n");
      out.write("            </li>\n");
      out.write("            <li data-toggle=\"tooltip\" title=\"Folow Us On Twitter\">\n");
      out.write("            <a href=\"#\" class=\"footer-social-icon-wrapper\">\n");
      out.write("            <span class=\"footer-icon-wrap\"></span>\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" focusable=\"false\" tabindex=\"-1\" width=\"24\" height=\"24\" viewBox=\"0 0 24\n");
      out.write("            24\"><path class=\"svg-color--primary\" fill=\"#fff\" d=\"M13 2C7.5 2 3 6.5 3 12s4.5 10 10 10 10-4.5 10-10S18.5 2 13\n");
      out.write("            2zm5.6 7.9v.4c0 4.4-3.6 7.9-8 7.9-1.6 0-3-.5-4.3-1.2h.4c1.4 0 2.7-.5 3.8-1.3h-.2c-1.2 0-2.2-.8-2.6-1.9h.5c.3 0\n");
      out.write("            .5 0 .8-.1-.5-.1-1-.3-1.4-.7-.5-.5-.9-1.2-.9-2v-.1c.4.2.8.3 1.3.3-.5-.3-.8-.7-1.1-1.1V9c0-.5.1-1\n");
      out.write("            .4-1.4.3.3.6.7.9.9l.2.2c.6.5 1.3.9 2.1 1.2.1 0 .2.1.3.1.3.1.7.2 1 .3.1 0 .2 0 .3.1.3 0 .6.1 1\n");
      out.write("            .1-.1-.2-.1-.5-.1-.7 0-.4.1-.8.2-1.1.1-.3.3-.6.5-.8.1-.1.2-.2.3-.2.3-.3.7-.5 1.1-.6.3-.1.5-.1.7-.1.8 0 1.5.4\n");
      out.write("            2.1.9.1 0 .2-.1.4-.1.5-.1 1-.3 1.4-.6 0 .1 0 .2-.1.2-.2.6-.6 1-1.1 1.3v.1c.5-.1 1-.2 1.5-.5-.4.6-.9 1.1-1.4\n");
      out.write("            1.6z\"></path></svg>\n");
      out.write("            <!--Twitter-->\n");
      out.write("            </a>\n");
      out.write("            </li>\n");
      out.write("            <li data-toggle=\"tooltip\" title=\"Folow Us On Linkedin\">\n");
      out.write("            <a href=\"#\" class=\"footer-social-icon-wrapper\">\n");
      out.write("            <span class=\"footer-icon-wrap\"></span>\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" focusable=\"false\" tabindex=\"-1\" width=\"24\" height=\"24\" viewBox=\"0 0 24\n");
      out.write("            24\"><path class=\"svg-color--primary\" fill=\"#fff\" d=\"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12\n");
      out.write("            2zM8.7 17.4H6.2V9.7h2.6v7.7zM7.4 8.7C6.6 8.7 6 8.1 6 7.3 6 6.6 6.6 6 7.5 6s1.4.6 1.4 1.3c0 .8-.6 1.4-1.5 1.4zM18\n");
      out.write("            17.4h-2.6v-4.1c0-1-.4-1.7-1.3-1.7-.7 0-1.1.5-1.3.9-.1.2-.1.4-.1.6v4.3h-2.6V9.7h2.6v1.1c.3-.5 1-1.3 2.3-1.3 1.7 0\n");
      out.write("            3 1.1 3 3.5v4.4z\"></path></svg>\n");
      out.write("            <!--Linkedin-->\n");
      out.write("            </a>\n");
      out.write("            </li>\n");
      out.write("            </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4 col-sm-12 links\">\n");
      out.write("            <ul class=\"items\">\n");
      out.write("            <li class=\"items-list\" >\n");
      out.write("            <a href=\"#\" data-toggle=\"tooltip\" title=\"About DewCis Solutions\"> Company </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"items-list\">\n");
      out.write("            <a href=\"#\"> Company </a>\n");
      out.write("            </li>\n");
      out.write("            </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4 col-sm-12 links\">\n");
      out.write("            <ul class=\"items\">\n");
      out.write("            <li class=\"items-list\">\n");
      out.write("            <a href=\"#\" data-toggle=\"tooltip\" title=\"Human Capital Management System\"> Baraza HCM </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"items-list\">\n");
      out.write("            <a href=\"#\" data-toggle=\"tooltip\" title=\"Sacco Management System\"> Baraza Sacco </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"items-list\">\n");
      out.write("            <a href=\"#\" data-toggle=\"tooltip\" title=\"Chama Management System\"> Baraza Chama </a>\n");
      out.write("            </li>\n");
      out.write("            </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4 col-sm-12\"></div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <!--Primary footer-->\n");
      out.write("            <div class=\"bottom-footer\">\n");
      out.write("            <div class=\"centralised central\">\n");
      out.write("            <div class=\"col-md-12 col-sm-12 center-wrapper\">\n");
      out.write("            <h3 class=\"footer-logo\">NAKAWA HOTELS</h3>\n");
      out.write("            <span class=\"footer-copywrite\">\n");
      out.write("            Copyright &copy; 2017 Nakawa Hotels | All rights reserved.\n");
      out.write("            </span>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!--/FOOTER-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Jquery-->\n");
      out.write("        <script src=\"./assets/vendor/jquery/dist/jquery.min.js\" ></script>\n");
      out.write("        <script src=\"./assets/vendor/bootstrap/dist/js/bootstrap.min.js\" ></script>\n");
      out.write("        <script src=\"./assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js\" ></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"./assets/vendor/bootstrap-slider/dist/bootstrap-slider.min.js\"></script>\n");
      out.write("        \n");
      out.write("        <script src=\"./assets/vendor/select2/dist/js/select2.min.js\" ></script>\n");
      out.write("        <script src=\"./assets/js/datepicker-tooltip-custom.js\" ></script>\n");
      out.write("\n");
      out.write("        <!--GOOGLE MAPS [Keysa International]-->\n");
      out.write("        <script async defer\n");
      out.write("        src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAzq8519ZIlWJVJnQ6XsTJfAqxvUYsX20o&callback=initMap\">\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("    <!--CUSTOM-->\n");
      out.write("    <script src=\"assets/js/ajax/auth.js\" ></script>\n");
      out.write("    <script src=\"./assets/vendor/intl-tel-input/build/js/intlTelInput.min.js\" ></script>\n");
      out.write("    <script src=\"./assets/js/validators/passwordMatchValidator.js\" ></script>\n");
      out.write("    <script src=\"./assets/js/validators/emailValidator.js\" ></script>\n");
      out.write("    <script src=\"./assets/js/validators/action/register.js\" ></script>\n");
      out.write("    <script>\n");
      out.write("    $(\"#phone\").intlTelInput({\n");
      out.write("        utilsScript: \"./assets/vendor/intl-tel-input/build/js/utils.js\"\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /./assets/includes/menu.jsp(24,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\n");
          out.write("                    <li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /./assets/includes/menu.jsp(28,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLogin != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <li class=\"dropdown dropdown-account\"><a href=\"#\" style=\"min-height: 50px;padding: 0px;\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" style=\"min-height: 50px;\"><span class=\"username username-hide-on-mobile\" style=\"color:#fff\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</span><img alt=\"\" class=\"img-circle\" src=\"./assets/admin-backend/img/avatar.png\"></a>\n");
          out.write("                    <ul class=\"dropdown-menu\">\n");
          out.write("                        <li><a href=\"dash\"><span class=\"glyphicon glyphicon-dashboard evin-space\"></span> Dashboard</a></li>\n");
          out.write("                        <li class=\"divider\"></li>\n");
          out.write("                        <li><a href=\"profile\"> <span class=\"glyphicon glyphicon-cog evin-space\"></span> Account Settings</a></li>\n");
          out.write("                        <li class=\"divider\"></li>\n");
          out.write("                        <li><a href=\"my_bookings?view=bookings\"><span class=\"glyphicon glyphicon-hdd evin-space\"></span> My Bookings <span class=\"badge badge-success evin-badge\">3 </span></a></li>\n");
          out.write("                        <li class=\"divider\"></li>\n");
          out.write("                        <li><a href=\"auth?tag=logout\" ><span class=\"glyphicon glyphicon-log-out evin-space\"></span> Sign Out </a></li>\n");
          out.write("                    </ul>\n");
          out.write("                    </li>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /./assets/includes/menu.jsp(29,248) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
